spring:
  application:
    name: ActividadMicroServicios

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: jdbc:mysql://localhost:3306/productos_db
    username: root
    password: mia1234567
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO
    com.example: DEBUG
